### ISSUE TITLE
npm run build on Win10

### ISSUE THREAD

**Issue by DestBest** [bitshares/bitsharesjs-ws#1]
Got the following error:

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! bitsharesjs-ws@1.0.3 prebuild: `npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitsharesjs-ws@1.0.3 prebuild script 'npm run clean'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bitsharesjs-ws package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean

**Comment by svk31** [comment]
That script won't run on Windows, you can remove it from your package json until I get a chance to update it.

**Comment by DestBest** [comment]
Will do
Thank you for the help 👍
