### ISSUE TITLE
Code  Problem

### ISSUE THREAD

**Issue by ying2025** [bitshares/bitsharesjs-ws#24]
I cannot understand how can you send message from client to server by WebSocket in ChainWebSocket.js.
And why you set the following variable quantity
this.send_life & this.recv_life
this.current_reject
this.keepalive_timer

**Comment by ying2025** [comment]
Is there any detail  document to unscramble bitsharesjs-ws source code ?

**Comment by scientistnik** [comment]
My suppose:
`recv_life` and `send_life` is different variable. One say that we don't receive `ping-pong` messages long time, and we need to check connection. Another variable, we have not connection to blockchain.

**Comment by sschiessl-bcp** [comment]
Thanks @scientistnik
