### ISSUE TITLE
Uglifying bitsharesjs-ws

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitsharesjs-ws#28]
@scientistnik 

Have you tried to uglify your refactored version (needed when being included in bitsharesjs)? It fails on my end, do you have any pointers?

`cross-env NODE_ENV=production uglifyjs --compress --mangle --sequences --drop_console --output build/bitsharesjs-ws.min.js -- build/bitsharesjs-ws.js`

**Comment by scientistnik** [comment]
`uglifyjs` has not developed for several years. it doesn't support ES6. `babel-minify` is best choice for that.

**Comment by sschiessl-bcp** [comment]
I see, thanks for clarification.

When I bundle bitsharesjs it tries to, I assume you haven't tried that? I agree it makes sense to switch to babel.

**Comment by scientistnik** [comment]
Yes, I haven't tried that.

**Comment by sschiessl-bcp** [comment]
> Yes, I haven't tried that.

babel seems to work. 

What was the reason that you have abandoned the Classes completely?

**Comment by scientistnik** [comment]
No, I don't. Classes is best choose, then you need several [similar object](https://github.com/bitshares/bitsharesjs-ws/blob/develop/src/GrapheneApi.js). But if you need Singleton, maybe best choose is use functions without classes.

**Comment by sschiessl-bcp** [comment]
Thanks
