### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ronenteva** [bitshares/bitsharesjs-ws#3]
Is there any documentation on how to use this package?
Please note that there's no option for posting issues on the package `bitsharesjs`

**Comment by svk31** [comment]
Not beyond what's in the README and the examples and tests, but that should be sufficient. I've enabled issues on `bitsharesjs` now.

**Comment by ronenteva** [comment]
For example, how can I get the latest offers between BTC and ETH using `bitsharesjs`?
How can I find the answer by reading the README and the examples?

**Comment by ronenteva** [comment]
Moving the question to bitshares/bitsharesjs#4
