### ISSUE TITLE
require('../cjs) in examples

### ISSUE THREAD

**Issue by benjamin852** [bitshares/bitsharesjs-ws#31]
Hi. I am having trouble running the accountIteration.js example because the require('../cjs') statement cannot find the cjs file and I see it is in the .gitignore file from when I cloned the repo. Anyway I can get access to this file so I can run the code?

Thank You
-Ben

**Comment by sschiessl-bcp** [comment]
> Hi. I am having trouble running the accountIteration.js example because the require('../cjs') statement cannot find the cjs file and I see it is in the .gitignore file from when I cloned the repo. Anyway I can get access to this file so I can run the code?
> 
> Thank You
> -Ben

Please clone the repository and install it. Then the cjs should be built.
