### ISSUE TITLE
The address prefix is not completely replaced, causing some tests of `bitsharesjs` to fail.

### ISSUE THREAD

**Issue by xiangxn** [bitshares/bitsharesjs-ws#42]
The address prefix is not completely replaced, causing some tests to fail.
see
https://github.com/bitshares/bitsharesjs-ws/blob/develop/src/ChainConfig.js#L3
https://github.com/bitshares/bitsharesjs-ws/blob/develop/src/ChainConfig.js#L43

**Comment by sschiessl-bcp** [comment]
Please set the config directly from bitsharesjs in the meantime

**Comment by xiangxn** [comment]
Thank you, the problem has been resolved.
