### ISSUE TITLE
Manager check connections -> 0 invalid -> multiple unreachable?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitsharesjs-ws#49]
Anyone experience any issues with `Manager.checkConnections()`?

All 7 nodes for me will pass, but then when I try to connect immediately after lag checking several of the nodes will timeout.

Are these ws servers potentially blocking my ip if I'm connecting shortly after a connection check? Or perhaps the ws connections aren't closing properly or are lingering, causing later connection issues?

Trying to add the node lag checks to beet, but it's got to cycle through multiple bad (passed) nodes before working..

**Comment by abitmore** [comment]
Can we leave the connections connected for a while after checking, so that no need to reconnect again later?

**Comment by sschiessl-bcp** [comment]
IIRC checkConnections pings differently than the UI does, and also pinging several was not reliable in results.
